#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class UndoHistory {
public:
  int minPresses(vector <string> V) {
    int c = 0;
    set<string> U;
    U.insert("");
    string bfr = "meh", meh;
    
    // for(int i=0; i<V.size(); i++) {
    //   for(int j=i+1; j<V.size(); j++) {
    // 	if(V[i].length() < V[j].length()) {
    // 	  meh = V[i];
    // 	  V[i] = V[j];
    // 	  V[j] = meh;
    // 	}
    //   }
    // }

    for(int i=0; i<V.size(); i++) {
      string s = V[i];
      bool sw = true;

      if(V[i].length() >= bfr.length()) {
	if(V[i].substr(0, bfr.length()) == bfr) {
	  cout << "o_O" << endl;
	  c += V[i].length() - bfr.length();
	  c -= 2;
	  bfr = V[i];

	  for(int k=bfr.length()+1; k<=V[i].length(); i++) {
	    cout << " --- " << s.substr(0, k) << " ---" << endl;
	    U.insert(s.substr(0, k));
	  }

	  cout << "c = " << c << endl;
	  continue;
	}
      }


      for(int j=s.length(); j>=1; j--) {

	cout << " >> " << s.substr(0, j) << endl;

	if(U.count(s.substr(0, j)) > 0) {
	  cout << " >>> " << s.substr(0, j) << endl;
	  sw = false;
	  c += s.length() - j;

	  for(int k=s.length(); k>j; k--) {
	    cout << " --- " << s.substr(0, k) << " ---" << endl;
	    U.insert(s.substr(k));
	  }
	  break;
	}
      }

      if(sw) {
	c += s.length();
	for(int k=s.length(); k>=1; k--) {
	  cout << " --- " << s.substr(0, k) << " ---" << endl;
	  U.insert(s.substr(0, k));
	}
      }

      bfr = s;
      cout << "c = " << c << endl;
    }

    return c + V.size() + V.size() * 2 - 2;
  }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	UndoHistory *obj;
	int answer;
	obj = new UndoHistory();
	clock_t startTime = clock();
	answer = obj->minPresses(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	int p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"tomorrow","topcoder"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 18;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"a","b"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 6;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"a","ab","abac","abacus"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 10;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"pyramid","sphinx","sphere","python","serpent"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 39;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"ba","a","a","b","ba"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 13;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	string t0[] = {"absolutely","abs","absolute"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 17;
	all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
